spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/ddyin?allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    max-active: 300
    max-idle: 10
    min-idle: 8
    username: root
    password: 11
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    validation-query: select 1
    filters: stat
    max-wait: 60000
    pool-prepared-statements: true
  task:
    pool:
      corePoolSize: 10
      maxPoolSize: 50
      keepAliveSeconds: 300
      queueCapacity: 1000
server:
  port: 9090
logging:
  level:
    ROOT: info
    tk:
      mybatis: TRACE
mybatis:
  type-aliases-package: com.ddyin.demo.dao.mapper
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml